/**
 * This code was generated by Builder.io.
 */
import React from 'react';

const BillingDetails = () => {
  return (
    <div style={{
      display: "flex",
      flexDirection: "column",
      lineHeight: "normal",
      width: "50%",
      marginLeft: "0px",
      "@media (max-width: 991px)": {
        width: "100%",  
      },
    }}>
      <div style={{
        display: "flex",
        width: "100%",
        flexDirection: "column",
        color: "var(--Light-Colors-Dark-gray---Light, #707070)",
        font: "400 16px/2 DM Sans, sans-serif",
        "@media (max-width: 991px)": {
          maxWidth: "100%",
          marginTop: "40px",
        },
      }}>
        <div style={{
          display: "flex",
          gap: "40px",
          flexWrap: "wrap",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }}>
          <div style={{
            display: "flex",
            flexDirection: "column",
            flex: "1",
            flexGrow: "1",
            flexBasis: "0",
            width: "fit-content",
          }}>
            <div style={{ alignSelf: "start" }}>First name *</div>
            <div style={{
              backgroundColor: "#d8d8d8",
              marginTop: "11px",
              height: "1px",
              border: "1px solid rgba(216, 216, 216, 1)",
            }} />
          </div>
          <div style={{
            display: "flex",
            flexDirection: "column",
            flex: "1",
            flexGrow: "1",
            flexBasis: "0",
            width: "fit-content",
          }}>
            <div style={{ alignSelf: "start" }}>last name *</div>
            <div style={{
              backgroundColor: "#d8d8d8",
              marginTop: "11px",
              height: "1px",
              border: "1px solid rgba(216, 216, 216, 1)",
            }} />
          </div>
        </div>
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Company Name</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{
          display: "flex",
          marginTop: "37px",
          gap: "20px",
          flexWrap: "wrap",
          justifyContent: "space-between",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }}>
          <div>Country *</div>
          <img loading="lazy" src="http://b.io/ext_13-" alt="" style={{
            aspectRatio: "1.67",
            objectFit: "contain",
            objectPosition: "center",
            width: "10px",
            fill: "var(--Light-Colors-Black---Light, #000)",
            margin: "auto 0",
          }} />
        </div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Street Address *</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Postcode / ZIP *</div>
        
          <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Town / City *</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Phone *</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Email *</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
        <div style={{
          alignSelf: "start",
          display: "flex",
          marginTop: "36px",
          gap: "8px",
          color: "var(--Light-Colors-Black---Light, #000)",
        }}>
          <div style={{
            borderRadius: "2px",
            border: "1px solid var(--Light-Colors-Dark-gray---Light, #707070)",
            display: "flex",
            width: "16px",
            height: "16px",
            margin: "auto 0",
          }} />
          <div style={{ flexBasis: "auto" }}>Create an acoount?</div>
        </div>
        <div style={{
          alignSelf: "start",
          display: "flex",
          marginTop: "18px",
          gap: "8px",
          color: "var(--Light-Colors-Black---Light, #000)",
        }}>
          <div style={{
            borderRadius: "2px",
            border: "1px solid var(--Light-Colors-Dark-gray---Light, #707070)",
            display: "flex",
            width: "16px",
            height: "16px",
            margin: "auto 0",
          }} />
          <div style={{ flexBasis: "auto" }}>Ship to a different address?</div>
        </div>
        <div style={{ alignSelf: "start", marginTop: "37px" }}>Order notes</div>
        <div style={{
          backgroundColor: "#d8d8d8",
          marginTop: "11px",
          height: "1px",
          border: "1px solid rgba(216, 216, 216, 1)",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
          },
        }} />
      </div>
    </div>
  );
};

export default BillingDetails;