/**
 * This code was generated by Builder.io.
 */
import React from "react";

const OrderSummary = () => {
  return (
    <div
      style={{
        display: "flex",
        lineHeight: "normal",
        width: "50%",
        marginLeft: "20px",
        "@media (max-width: 991px)": {
          width: "100%",
        },
      }}
    >
      <div
        style={{
          background: "var(--Light-Colors-Light-gray---Light, #efefef)",
          backgroundColor: "var(--Light-Colors-Light-gray---Light, #efefef)",
          display: "flex",
          width: "100%",
          flexDirection: "column",
          margin: "0 auto",
          padding: "44px 59px",
          font: "400 16px/2 DM Sans, sans-serif",
          "@media (max-width: 991px)": {
            maxWidth: "100%",
            marginTop: "40px",
            padding: "0 20px",
          },
        }}
      >
        <div
          style={{
            display: "flex",
            gap: "20px",
            color: "var(--Light-Colors-Black---Light, #000)",
            whiteSpace: "nowrap",
            justifyContent: "space-between",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              whiteSpace: "initial",
            },
          }}
        >
          <div>PRODUCT</div>
          <div>TOTAL</div>
        </div>
        <div
          style={{
            backgroundColor: "#d8d8d8",
            marginTop: "17px",
            width: "462px",
            maxWidth: "100%",
            height: "1px",
            border: "1px solid rgba(216, 216, 216, 1)",
            "@media (max-width: 991px)": {
              marginRight: "2px",
            },
          }}
        />
        <div
          style={{
            display: "flex",
            marginTop: "22px",
            gap: "20px",
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            justifyContent: "space-between",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
            },
          }}
        >
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "start",
            }}
          >
            <div>Lira Earrings</div>
            <div style={{ marginTop: "26px" }}>Ollie Earrings</div>
            <div style={{ alignSelf: "stretch", marginTop: "26px" }}>
              Kaede Hair Pin
            </div>
          </div>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              whiteSpace: "nowrap",
              "@media (max-width: 991px)": {
                whiteSpace: "initial",
              },
            }}
          >
            <div>$64</div>
            <div
              style={{
                display: "flex",
                marginTop: "26px",
                paddingLeft: "5px",
                flexDirection: "column",
                alignItems: "start",
                "@media (max-width: 991px)": {
                  whiteSpace: "initial",
                },
              }}
            >
              <div>$10</div>
              <div style={{ marginTop: "26px" }}>$10</div>
            </div>
          </div>
        </div>
        <div
          style={{
            backgroundColor: "#d8d8d8",
            marginTop: "11px",
            width: "462px",
            maxWidth: "100%",
            height: "1px",
            border: "1px solid rgba(216, 216, 216, 1)",
            "@media (max-width: 991px)": {
              marginRight: "2px",
            },
          }}
        />
        <div
          style={{
            display: "flex",
            marginTop: "14px",
            gap: "20px",
            whiteSpace: "nowrap",
            justifyContent: "space-between",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              marginRight: "2px",
              whiteSpace: "initial",
            },
          }}
        >
          <div style={{ color: "var(--Light-Colors-Black---Light, #000)" }}>
            SUBTOTAL
          </div>
          <div
            style={{ color: "var(--Light-Colors-Dark-gray---Light, #707070)" }}
          >
            $85
          </div>
        </div>
        <div
          style={{
            backgroundColor: "#d8d8d8",
            marginTop: "9px",
            width: "462px",
            maxWidth: "100%",
            height: "1px",
            border: "1px solid rgba(216, 216, 216, 1)",
            "@media (max-width: 991px)": {
              marginRight: "2px",
            },
          }}
        />
        <div
          style={{
            display: "flex",
            marginTop: "14px",
            gap: "20px",
            justifyContent: "space-between",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              marginRight: "3px",
            },
          }}
        >
          <div style={{ color: "var(--Light-Colors-Black---Light, #000)" }}>
            SHIPPING
          </div>
          <div
            style={{ color: "var(--Light-Colors-Dark-gray---Light, #707070)" }}
          >
            Free shipping
          </div>
        </div>
        <div
          style={{
            backgroundColor: "#d8d8d8",
            marginTop: "9px",
            width: "462px",
            maxWidth: "100%",
            height: "1px",
            border: "1px solid rgba(216, 216, 216, 1)",
            "@media (max-width: 991px)": {
              marginRight: "2px",
            },
          }}
        />
        <div
          style={{
            display: "flex",
            marginTop: "24px",
            gap: "20px",
            color: "var(--Light-Colors-Black---Light, #000)",
            fontWeight: "700",
            whiteSpace: "nowrap",
            justifyContent: "space-between",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              marginRight: "2px",
              whiteSpace: "initial",
            },
          }}
        >
          <div>TOTAL</div>
          <div style={{ textTransform: "capitalize" }}>$85</div>
        </div>
        <div
          style={{
            alignSelf: "start",
            display: "flex",
            marginTop: "61px",
            gap: "8px",
            color: "var(--Light-Colors-Black---Light, #000)",
            "@media (max-width: 991px)": {
              marginTop: "40px",
            },
          }}
        >
          <img
            loading="lazy"
            src="http://b.io/ext_14-"
            alt=""
            style={{
              aspectRatio: "1",
              objectFit: "contain",
              objectPosition: "center",
              width: "16px",
              fill: "var(--Light-Colors-Black---Light, #000)",
              margin: "auto 0",
            }}
          />
          <div style={{ flexBasis: "auto" }}>Direct bank transfer</div>
        </div>
        <div
          style={{
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            fontSize: "12px",
            lineHeight: "20px",
            marginTop: "19px",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              marginRight: "7px",
            },
          }}
        >
          Make your payment directly into our bank account. Please use your
          Order ID as the payment reference. Your order will not be shipped
          until the funds have cleared in our account.
        </div>
        <div
          style={{
            alignSelf: "start",
            display: "flex",
            marginTop: "25px",
            gap: "8px",
            color: "var(--Light-Colors-Black---Light, #000)",
          }}
        >
          <img
            loading="lazy"
            src="http://b.io/ext_15-"
            alt=""
            style={{
              aspectRatio: "1",
              objectFit: "contain",
              objectPosition: "center",
              width: "16px",
              fill: "var(--Light-Colors-Black---Light, #000)",
              margin: "auto 0",
            }}
          />
          <div style={{ flexBasis: "auto" }}>Check payments</div>
        </div>
        <div
          style={{
            alignSelf: "start",
            display: "flex",
            marginTop: "18px",
            gap: "8px",
            color: "var(--Light-Colors-Black---Light, #000)",
          }}
        >
          <img
            loading="lazy"
            src="http://b.io/ext_16-"
            alt=""
            style={{
              aspectRatio: "1",
              objectFit: "contain",
              objectPosition: "center",
              width: "16px",
              fill: "var(--Light-Colors-Black---Light, #000)",
              margin: "auto 0",
            }}
          />
          <div style={{ flexBasis: "auto" }}>Cash on delivery</div>
        </div>
        <div
          style={{
            alignSelf: "start",
            display: "flex",
            marginTop: "18px",
            alignItems: "center",
            gap: "8px",
            color: "var(--Light-Colors-Black---Light, #000)",
          }}
        >
          <img
            loading="lazy"
            src="http://b.io/ext_17-"
            alt=""
            style={{
              aspectRatio: "1",
              objectFit: "contain",
              objectPosition: "center",
              width: "16px",
              fill: "var(--Light-Colors-Black---Light, #000)",
              alignSelf: "stretch",
              margin: "auto 0",
            }}
          />
          <div style={{ alignSelf: "stretch" }}>PayPal</div>
          <img
            loading="lazy"
            src="http://b.io/ext_18-"
            alt=""
            style={{
              aspectRatio: "0.81",
              objectFit: "contain",
              objectPosition: "center",
              width: "13px",
              fill: "var(--Light-Colors-Black---Light, #000)",
              alignSelf: "stretch",
              margin: "auto 0",
            }}
          />
        </div>
        <button
          style={{
            borderRadius: "4px",
            border: "1px solid var(--Light-Colors-Black---Light, #000)",
            background: "var(--Light-Colors-Black---Light, #000)",
            backgroundColor: "var(--Light-Colors-Black---Light, #000)",
            marginTop: "45px",
            color: "var(--Light-Colors-White---Light, #fff)",
            fontWeight: "700",
            padding: "16px 70px",
            "@media (max-width: 991px)": {
              maxWidth: "100%",
              margin: "40px 2px 0 0",
              padding: "0 20px",
            },
          }}
        >
          PLACE ORDER
        </button>
      </div>
    </div>
  );
};

export default OrderSummary;
