/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CartItems = () => {
  const cartItems = [
    {
      id: 1,
      name: "Lira Earrings",
      color: "Black",
      size: "Medium",
      price: 20.0,
      quantity: 3,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/f1bb51e07d3fec2c980222cb5a092812489e1a401e71e4917bb6ba4ecad78638?placeholderIfAbsent=true&apiKey=b6276752b330489880794e71a32a87ff",
    },
    {
      id: 2,
      name: "Ollie Earrings",
      color: "Black",
      size: "Medium",
      price: 20.0,
      quantity: 1,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/b99eef8e517d6dcfb80b0c0c159f7dd0571dc4bccdc9927600b2e1239f661326?placeholderIfAbsent=true&apiKey=b6276752b330489880794e71a32a87ff",
    },
    {
      id: 3,
      name: "Kaede Hair Pin",
      color: "Black",
      size: "Medium",
      price: 20.0,
      quantity: 1,
      image:
        "https://cdn.builder.io/api/v1/image/assets/TEMP/d85854aecfe81a23e7735255b6c1d788e03b9b8f46a9b90997d2ac8856a9856b?placeholderIfAbsent=true&apiKey=b6276752b330489880794e71a32a87ff",
    },
  ];

  return (
    <div style={{ width: "50%" }}>
      {cartItems.map((item) => (
        <div
          key={item.id}
          style={{
            display: "flex",
            gap: "20px",
            marginBottom: "38px",
          }}
        >
          <img
            src={item.image}
            alt={item.name}
            style={{
              width: "136px",
              height: "136px",
              borderRadius: "4px",
              objectFit: "cover",
            }}
          />
          <div style={{ flexGrow: 1 }}>
            <h2
              style={{
                color: "var(--Light-Colors-Black---Light, #000)",
                fontSize: "20px",
                lineHeight: 1.3,
                margin: "0 0 14px",
              }}
            >
              {item.name}
            </h2>
            <p
              style={{
                color: "var(--Light-Colors-Dark-gray---Light, #707070)",
                font: "16px/2 DM Sans, sans-serif",
                margin: 0,
              }}
            >
              {item.color} / {item.size}
            </p>
            <p
              style={{
                color: "var(--Light-Colors-Accent---Light, #a18a68)",
                font: "16px/2 DM Sans, sans-serif",
                margin: 0,
              }}
            >
              $ {item.price.toFixed(2)}
            </p>
          </div>
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "24px",
              padding: "13px 16px",
              backgroundColor:
                "var(--Light-Colors-Light-gray---Light, #efefef)",
              borderRadius: "4px",
            }}
          >
            <button
              aria-label="Decrease quantity"
              style={{
                background: "none",
                border: "none",
                cursor: "pointer",
                font: "16px/2 DM Sans, sans-serif",
                color: "var(--Light-Colors-Dark-gray---Light, #707070)",
              }}
            >
              -
            </button>
            <span>{item.quantity}</span>
            <button
              aria-label="Increase quantity"
              style={{
                background: "none",
                border: "none",
                cursor: "pointer",
                font: "16px/2 DM Sans, sans-serif",
                color: "var(--Light-Colors-Dark-gray---Light, #707070)",
              }}
            >
              +
            </button>
          </div>
          <button
            aria-label="Remove item"
            style={{
              background: "none",
              border: "none",
              cursor: "pointer",
              padding: 0,
            }}
          >
            <img
              src="http://b.io/ext_15-"
              alt=""
              style={{ width: "13px", height: "14px" }}
            />
          </button>
        </div>
      ))}
      <button
        style={{
          borderRadius: "4px",
          border: "1px solid var(--Light-Colors-Black---Light, #000)",
          color: "var(--Light-Colors-Black---Light, #000)",
          padding: "16px 31px",
          font: "700 16px DM Sans, sans-serif",
          background: "none",
          cursor: "pointer",
          marginTop: "39px",
        }}
      >
        UPDATE CART
      </button>
      <div
        style={{
          display: "flex",
          marginTop: "64px",
          gap: "20px",
        }}
      >
        <input
          type="text"
          placeholder="Coupon Code"
          style={{
            flexGrow: 1,
            border: "none",
            borderBottom: "1px solid #d8d8d8",
            font: "12px/2 DM Sans, sans-serif",
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            padding: "8px 0",
          }}
        />
        <button
          style={{
            borderRadius: "4px",
            border: "1px solid var(--Light-Colors-Black---Light, #000)",
            backgroundColor: "var(--Light-Colors-Black---Light, #000)",
            color: "var(--Light-Colors-White---Light, #fff)",
            font: "700 16px DM Sans, sans-serif",
            padding: "16px 23px",
            cursor: "pointer",
          }}
        >
          APPLY COUPON
        </button>
      </div>
    </div>
  );
};

export default CartItems;
