/**
 * This code was generated by Builder.io.
 */
import React from "react";

const CartSummary = ({setChangeVue}) => {
  return (
    <div
      style={{
        width: "50%",
        padding: "44px 59px",
        borderRadius: "4px",
        backgroundColor: "var(--Light-Colors-White---Light, #fff)",
      }}
    >
      <h2
        style={{
          fontSize: "26px",
          lineHeight: 1,
          color: "var(--Light-Colors-Black---Light, #000)",
          margin: "0 0 44px",
        }}
      >
        Cart totals
      </h2>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          font: "16px/27px DM Sans, -apple-system, Roboto, Helvetica, sans-serif",
          marginBottom: "39px",
        }}
      >
        <span>SUBTOTAL</span>
        <span>$ 65,00</span>
      </div>
      <div
        style={{
          display: "flex",
          justifyContent: "space-between",
          font: "16px/27px DM Sans, -apple-system, Roboto, Helvetica, sans-serif",
          marginBottom: "39px",
        }}
      >
        <span>SHIPPING</span>
        <span>
          Shipping costs will be calculated once you have provided address.
        </span>
      </div>
      <button
        style={{
          color: "var(--Light-Colors-Black---Light, #000)",
          font: "400 16px/2 DM Sans, sans-serif",
          background: "none",
          border: "none",
          cursor: "pointer",
          display: "flex",
          alignItems: "center",
          gap: "10px",
          padding: 0,
          marginBottom: "31px",
        }}
      >
        CALCULATE SHIPPING
        <img
          src="http://b.io/ext_16-"
          alt=""
          style={{ width: "8px", height: "4px" }}
        />
      </button>
      <div style={{ marginBottom: "24px" }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            font: "400 12px/2 DM Sans, sans-serif",
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            borderBottom: "1px solid #d8d8d8",
            padding: "12px 0",
          }}
        >
          <span>SELECT A COUNTRY</span>
          <img
            src="http://b.io/ext_17-"
            alt=""
            style={{ width: "8px", height: "4px" }}
          />
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            font: "400 12px/2 DM Sans, sans-serif",
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            borderBottom: "1px solid #d8d8d8",
            padding: "12px 0",
          }}
        >
          <span>CITY</span>
          <img
            src="http://b.io/ext_17-"
            alt=""
            style={{ width: "8px", height: "4px" }}
          />
        </div>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            font: "400 12px/2 DM Sans, sans-serif",
            color: "var(--Light-Colors-Dark-gray---Light, #707070)",
            borderBottom: "1px solid #d8d8d8",
            padding: "12px 0",
          }}
        >
          <span>POST CODE / ZIP</span>
          <img
            src="http://b.io/ext_17-"
            alt=""
            style={{ width: "8px", height: "4px" }}
          />
        </div>
      </div>
      <button
        style={{
          borderRadius: "4px",
          border: "1px solid var(--Light-Colors-Black---Light, #000)",
          color: "var(--Light-Colors-Black---Light, #000)",
          padding: "16px 64px",
          font: "700 16px DM Sans, sans-serif",
          background: "none",
          cursor: "pointer",
          marginBottom: "38px",
        }}
      >
        UPDATE TOTALS
      </button>
      <div
        style={{
          borderTop: "1px solid #d8d8d8",
          paddingTop: "38px",
          display: "flex",
          justifyContent: "space-between",
          font: "700 16px DM Sans, sans-serif",
          color: "var(--Light-Colors-Black---Light, #000)",
        }}
      >
        <span>TOTAL</span>
        <span>$ 87,00</span>
      </div>
      <button onClick={()=>{setChangeVue("checkOut")
      window.scrollTo({ top: 0, behavior: 'smooth' })
      }}
        style={{
          borderRadius: "4px",
          border: "1px solid var(--Light-Colors-Black---Light, #000)",
          backgroundColor: "var(--Light-Colors-Black---Light, #000)",
          color: "var(--Light-Colors-White---Light, #fff)",
          padding: "16px 70px",
          font: "700 16px DM Sans, sans-serif",
          cursor: "pointer",
          width: "100%",
          marginTop: "54px",
        }}
      >
        PROCEED TO CHECKOUT
      </button>
    </div>
  );
};

export default CartSummary;
