/**
 * This code was generated by Builder.io.
 */
import React from "react";
import CartItems from "./CartItems";
import CartSummary from "./CartSummary";

const ShoppingCart = ({setChangeVue}) => {
  return (
    <main>
      
      <h1
        style={{
          color: "var(--Light-Colors-Black---Light, #000)",
          font: "500 33px/1.3 DM Sans, -apple-system, Roboto, Helvetica, sans-serif",
          margin: "96px 0 63px",
        }}
      >
        Shopping Cart
      </h1>
      <div
        style={{
          display: "flex",
          width: "100%",
          maxWidth: "1248px",
          gap: "20px",
        }}
      >
        <CartItems />
        <CartSummary setChangeVue={setChangeVue}/>
      </div>
    </main>
  );
};

export default ShoppingCart;
