/**
 * This code was generated by Builder.io.
 */
import React from "react";
import AccountNav from "./AccountNav";
import OrderStatus from "./OrderStatus";

const accountOrdersStyle = {
  background: "var(--Light-Colors-White---Light, #fff)",
  display: "flex",
  flexDirection: "column",
  overflow: "hidden",
  alignItems: "center",
  padding: "82px 80px",
};

const headerDividerStyle = {
  backgroundColor: "#d8d8d8",
  marginTop: "22px",
  width: "1248px",
  maxWidth: "100%",
  height: "1px",
  border: "1px solid rgba(216, 216, 216, 1)",
};

const orderImageStyle = {
  objectFit: "contain",
  objectPosition: "center",
  width: "100%",
  borderRadius: "0",
  marginTop: "34px",
  maxWidth: "1248px",
};

const accentDividerStyle = {
  backgroundColor: "#a18a68",
  zIndex: "10",
  marginTop: "38px",
  width: "1248px",
  maxWidth: "100%",
  height: "2px",
  border: "2px solid rgba(161, 138, 104, 1)",
};

const AccountOrders = () => {
  return (
    <main style={accountOrdersStyle}>
      <div style={headerDividerStyle} />
      <AccountNav />
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/01e45ace3a86ae8b477a804d2d8863b47cf2842ee6cdd2c9d75bc8f4c234ebe9?placeholderIfAbsent=true&apiKey=b6276752b330489880794e71a32a87ff"
        alt="Order details"
        style={orderImageStyle}
      />
      <div style={accentDividerStyle} />
      <OrderStatus />
    </main>
  );
};

export default AccountOrders;
