/**
 * This code was generated by Builder.io.
 */
import React from "react";

const accountNavStyle = {
  alignSelf: "start",
  display: "flex",
  marginTop: "99px",
  gap: "40px 49px",
  color: "var(--Light-Colors-Dark-gray---Light, #707070)",
  flexWrap: "wrap",
  font: "400 20px/1.3 DM Sans, -apple-system, Roboto, Helvetica, sans-serif",
};

const accountNavItemStyle = {
  flexGrow: "1",
  textDecoration: "none",
  color: "inherit",
};

const activeNavItemStyle = {
  ...accountNavItemStyle,
  color: "var(--Light-Colors-Black---Light, #000)",
};

const AccountNav = () => {
  const navItems = [
    { name: "Dashboard", active: false },
    { name: "Orders", active: true },
    { name: "Downloads", active: false },
    { name: "Addresses", active: false },
    { name: "Account details", active: false },
    { name: "Logout", active: false },
  ];

  return (
    <nav style={accountNavStyle}>
      {navItems.map((item, index) => (
        <a
          key={index}
          href="#"
          style={item.active ? activeNavItemStyle : accountNavItemStyle}
        >
          {item.name}
        </a>
      ))}
    </nav>
  );
};

export default AccountNav;
