/**
 * This code was generated by Builder.io.
 */
import React from "react";

const addressContainerStyle = {
  marginTop: "39px",
  width: "955px",
  maxWidth: "100%",
};

const addressColumnsStyle = {
  gap: "20px",
  display: "flex",
};

const billingColumnStyle = {
  display: "flex",
  flexDirection: "column",
  lineHeight: "normal",
  width: "67%",
  marginLeft: "0",
};

const billingDetailsStyle = {
  display: "flex",
  gap: "40px",
  fontFamily: "DM Sans, sans-serif",
  fontWeight: "400",
  flexWrap: "wrap",
};

const billingSectionStyle = {
  display: "flex",
  flexDirection: "column",
  alignItems: "start",
  flexGrow: "1",
  flexBasis: "0",
  width: "fit-content",
};

const sectionTitleStyle = {
  color: "var(--Light-Colors-Black---Light, #000)",
  fontSize: "20px",
  lineHeight: "1.3",
};

const inputLabelStyle = {
  color: "var(--Light-Colors-Dark-gray---Light, #707070)",
  fontSize: "16px",
  lineHeight: "2",
  marginTop: "24px",
};

const inputUnderlineStyle = {
  backgroundColor: "#d8d8d8",
  alignSelf: "stretch",
  marginTop: "11px",
  height: "1px",
  border: "1px solid rgba(216, 216, 216, 1)",
  width: "100%",
};

const shippingColumnStyle = {
  display: "flex",
  flexDirection: "column",
  lineHeight: "normal",
  width: "33%",
  marginLeft: "20px",
};

const shippingDetailsStyle = {
  display: "flex",
  flexGrow: "1",
  flexDirection: "column",
  alignItems: "start",
  fontFamily: "DM Sans, sans-serif",
  fontWeight: "400",
};

const addButtonStyle = {
  color: "var(--Light-Colors-Accent---Light, #a18a68)",
  fontSize: "16px",
  fontWeight: "700",
  marginTop: "24px",
  background: "none",
  border: "none",
  cursor: "pointer",
};

const shippingMessageStyle = {
  color: "var(--Light-Colors-Dark-gray---Light, #707070)",
  fontSize: "14px",
  lineHeight: "2",
  alignSelf: "stretch",
  marginTop: "14px",
};

const countrySelectorStyle = {
  display: "flex",
  marginTop: "37px",
  width: "580px",
  maxWidth: "100%",
  gap: "20px",
  color: "var(--Light-Colors-Dark-gray---Light, #707070)",
  flexWrap: "wrap",
  justifyContent: "space-between",
  font: "400 16px/2 DM Sans, sans-serif",
};

const dropdownIconStyle = {
  aspectRatio: "1.67",
  objectFit: "contain",
  objectPosition: "center",
  width: "10px",
  fill: "var(--Light-Colors-Black---Light, #000)",
  margin: "auto 0",
};

const saveButtonStyle = {
  borderRadius: "4px",
  border: "1px solid var(--Light-Colors-Black---Light, #000)",
  background: "var(--Light-Colors-Black---Light, #000)",
  marginTop: "64px",
  color: "var(--Light-Colors-White---Light, #fff)",
  padding: "16px 64px",
  font: "700 16px DM Sans, sans-serif",
  cursor: "pointer",
};

const AddressForm = () => {
  const billingFields = [
    { label: "First name *", id: "firstName" },
    { label: "Last name *", id: "lastName" },
  ];

  const shippingFields = [
    { label: "Company Name", id: "companyName" },
    { label: "Country *", id: "country", type: "select" },
    { label: "Street Address *", id: "streetAddress" },
    { label: "Postcode / ZIP *", id: "postcode" },
    { label: "Town / City *", id: "city" },
    { label: "Phone *", id: "phone" },
    { label: "Email *", id: "email" },
  ];

  return (
    <form style={addressContainerStyle}>
      <div style={addressColumnsStyle}>
        <div style={billingColumnStyle}>
          <div style={billingDetailsStyle}>
            <div style={billingSectionStyle}>
              <h2 style={sectionTitleStyle}>Billing Address</h2>
              {billingFields.map((field) => (
                <div key={field.id}>
                  <label htmlFor={field.id} style={inputLabelStyle}>
                    {field.label}
                  </label>
                  <input
                    type="text"
                    id={field.id}
                    style={inputUnderlineStyle}
                  />
                </div>
              ))}
            </div>
          </div>
        </div>
        <div style={shippingColumnStyle}>
          <div style={shippingDetailsStyle}>
            <h2 style={sectionTitleStyle}>Shipping Address</h2>
            <button type="button" style={addButtonStyle}>
              ADD
            </button>
            <p style={shippingMessageStyle}>
              You have not set up this type of address yet.
            </p>
          </div>
        </div>
      </div>
      {shippingFields.map((field) => (
        <div key={field.id}>
          <label htmlFor={field.id} style={inputLabelStyle}>
            {field.label}
          </label>
          {field.type === "select" ? (
            <div style={countrySelectorStyle}>
              <select id={field.id} style={inputUnderlineStyle}>
                <option value="">Select a country</option>
              </select>
              <img src="http://b.io/ext_12-" alt="" style={dropdownIconStyle} />
            </div>
          ) : (
            <input type="text" id={field.id} style={inputUnderlineStyle} />
          )}
        </div>
      ))}
      <button type="submit" style={saveButtonStyle}>
        SAVE ADDRESS
      </button>
    </form>
  );
};

export default AddressForm;
