/**
 * This code was generated by Builder.io.
 */
import React from "react";

const navigationMenuStyle = {
  display: "flex",
  marginTop: "99px",
  gap: "40px 49px",
  color: "var(--Light-Colors-Dark-gray---Light, #707070)",
  flexWrap: "wrap",
  font: "400 20px/1.3 DM Sans, -apple-system, Roboto, Helvetica, sans-serif",
};

const navItemStyle = {
  textDecoration: "none",
  color: "inherit",
};

const activeNavItemStyle = {
  ...navItemStyle,
  color: "var(--Light-Colors-Black---Light, #000)",
};

const NavigationMenu = ({setChangeVue}) => {
 

  return (
    <nav style={navigationMenuStyle}>
       <a>
       Dashboard
        </a>
        <a onClick={()=>{
              setChangeVue("myOrders")
              window.scrollTo({ top: 0, behavior: 'smooth' })
            }}>
        Orders
        </a>
        <a>
        Downloads
        </a>
        <a>
        Addresses
        </a>
        <a>
        Account details
        </a>
        <a>
        Logout
        </a>
    </nav>
  );
};

export default NavigationMenu;

